version: "3.1"

services:
  router:
    image: nginx:1.17-alpine
    volumes:
      - ./mock-router.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8079:80"

  employees_mock:
    image: openjdk:13-alpine
    container_name: employees_mock
    command: java -jar /app/karate-0.9.1.jar -m /app/employees-mock.feature -p 8080
    ports:
      - "8087:8080"
    volumes:
      - .:/app

  employees_contract:
    image: openjdk:13-alpine
    command: java -jar -Dlogback.configurationFile=/app/logback-test.xml -Dkarate.config.dir=/app /app/karate-0.9.5.jar -T 5 /app/contract-tests/employees-contract.feature
    volumes:
      - .:/app
  
  employees_filter_contract:
    image: openjdk:13-alpine
    command: java -jar -Dlogback.configurationFile=/app/logback-test.xml -Dkarate.config.dir=/app /app/karate-0.9.5.jar -T 5 /app/contract-tests/employees-filter-contract.feature
    volumes:
      - .:/app
